{% if GIT_DESCRIBE_NUMBER > '0' %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] + '.post' + GIT_DESCRIBE_NUMBER %}
{% else %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] %}
{% endif %}
{% set PKG_NAME = 'paho-mqtt-helpers' %}
{% set MODULE_NAME = PKG_NAME.replace('-', '_') %}
package:
  name: {{ PKG_NAME }}
  version: {{ GIT_VERSION }}

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  #: .. versionadded:: 0.3
  noarch: python

requirements:
  build:
    - python >=3.6
    - versioneer
    - mqtt-messages-python
    - paho-mqtt
    - pandas-helpers
    - wheezy.routing
  run:
    - python >=3.6
    - versioneer
    - mqtt-messages-python
    - paho-mqtt
    - pandas-helpers
    - wheezy.routing

test:
  imports:
    - {{ MODULE_NAME }}

about:
  home: https://github.com/Lucaszw/paho-mqtt-helpers.git
  license: BSD
  summary: Base functionality for MQTT reactor (i.e., a process to listen/react to MQTT topic messages).

# source will be downloaded prior to filling in jinja templates
# Example assumes that this folder has setup.py in it
source:
  git_url: ../
