{% if GIT_DESCRIBE_NUMBER > '0' %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] + '.post' + GIT_DESCRIBE_NUMBER %}
{% else %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] %}
{% endif %}
# source will be downloaded prior to filling in jinja templates
# Example assumes that this folder has setup.py in it
source:
  git_url: ../

package:
  name: paho-mqtt-helpers
  version: {{ GIT_VERSION }}

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  #: .. versionadded:: 0.3
  noarch: python

requirements:
  build:
    #: .. versionadded:: 0.3.1
    - mqtt-messages-python >=0.2
    - paho-mqtt >=1.3.1
    #: .. versionadded:: 0.3.1
    - pandas-helpers >=0.3
    - python
    #: .. versionadded:: 0.3
    - six
    #: .. versionadded:: 0.3
    - versioneer
    #: .. versionadded:: 0.3.1
    - wheezy.routing >=0.1.157
  run:
    - mqtt-messages-python >=0.2
    - paho-mqtt >=1.3.1
    - pandas-helpers >=0.3
    - python
    #: .. versionadded:: 0.3
    - six
    #: .. versionadded:: 0.3
    - versioneer
    - wheezy.routing >=0.1.157

test:
  imports:
    - paho_mqtt_helpers

about:
  home: https://github.com/Lucaszw/paho-mqtt-helpers.git
  license: BSD
